# User config
author: "Katrien Hardeman"
tagline: "Creatief vertaalster"
description: "Creatief vertaalster in de Romaanse talen en (eind)redactrice met expertise in  non-fictie. Werkt als freelancer voor verschillende Vlaamse en Nederlandse uitgeverijen en organisaties."
email: "hardeman.katrien@skynet.be"
linkedin: "https://www.linkedin.com/in/katrienhardeman"
twitter: "https://metadata.isbn.nl/28322/katrien-hardeman.html"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
