# User config
author: "Katrien Hardeman"
tagline: "Creatief vertaalster"
description: "Creatief verstaalster in de Romaanse talen, mijn kinderen zijn supercool."
email: "katrien@hardeman.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
